name: Déploiement sur Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Déployer le backend sur Render via l'API
        run: |
          curl ${{ secrets.RENDER_SERVICE_ID_BACKEND }}

  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Déployer le frontend sur Render via l'API
        run: |
          curl ${{ secrets.RENDER_SERVICE_ID_FRONTEND }}
