name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vote-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  

      - name: Install Dependencies (Go)
        run: |
          cd ./vote-api
          go mod tidy  

      - name: Build the Docker image for vote-api
        run: |
          cd ./vote-api
          docker build -t vote-api .  

      - name: Run Unit Tests (Go)
        run: |
          cd ./vote-api
          go test ./...  # Exécuter les tests unitaires pour le backend

  # Job pour le frontend (`web-client`)
  web-client:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  

      - name: Install Dependencies (Frontend)
        run: |
          cd ./web-client
          yarn install  

      - name: Build the Docker image for web-client
        run: |
          cd ./web-client
          docker build -t web-client . 

      - name: Run Unit Tests (Vitest)
        run: |
          cd ./web-client
          yarn test





