ame: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vote-api:
    runs-on: ubuntu-latest
    working-directory: ./vote-api  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  

      - name: Install Dependencies (Go)
        run: |
          go mod tidy  # Mettre à jour les dépendances Go

      - name: Build the Docker image for vote-api
        run: |
          docker build -t vote-api .  # Construire l'image Docker pour le backend

      - name: Run Unit Tests (Go)
        run: |
          go test ./...  # Exécuter les tests unitaires pour le backend

  # Job pour le frontend (`web-client`)
  web-client:
    runs-on: ubuntu-latest
    working-directory: ./web-client  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  

      - name: Install Dependencies (Frontend)
        run: |
          yarn install  # Installer les dépendances pour le frontend

      - name: Build the Docker image for web-client
        run: |
          docker build -t web-client . 

      - name: Run Unit Tests (Vitest)
        run: |
          yarn test